### ISSUE TITLE
Peer-to-peer-code-review-week-4-module-2-thur

### ISSUE THREAD

**Issue by johnkioko** [oguntayomicheal/Leaderboard#4]
Hello @oguntayomicheal! Amazing job in the below 👏 

- Using HTML 5 Semantics
- Following JS best practices
- Using ES6 arrow functions in your project

Just follow the below permalink to check if that line of code has any job in your codebase and if not you can do away with it.
https://github.com/oguntayomicheal/Leaderboard/blob/cc9e0988110282313ac591ee977f420feaf60c0c/src/index.js#L3

**Comment by oguntayomicheal** [comment]
Hello @johnkioko, thanks for the issue created.
